modLoader = "javafml"
loaderVersion = "[38,)"
license = "LGPLv3"

[[mods]]
modId = "malilib"
version = "${version}"
displayName = "MaLiLib-Forge"
displayURL="https://github.com/ThinkingStudios/MaLiLib-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
MaLiLib unofficial Forge port.

A library mod required by masa's client-side mods.
'''

[[dependencies.malilib]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.malilib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.malilib]]
modId = "forgedfabricloader"
mandatory = true
versionRange = "[0.1.2,)"
ordering = "NONE"
side = "BOTH"
