modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"

[[mods]]
modId = "malilib"
version = "${version}"
displayName = "MaLiLib"
displayURL="https://changeme.dev/" #optional
logoFile="assets/malilib/icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
MaLiLib unoffical Forge port.

A library mod required by masa's client-side mods.
'''

[[dependencies.malilib]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.malilib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
