modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"

[[mods]]
modId = "mafglib"
version = "${version}"
displayName = "MaFgLib"
displayURL="https://github.com/ThinkingStudios/MaLiLib-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
MaLiLib unofficial Forge port.

A library mod required by masa's client-side mods.
'''

[[mixins]]
config = "mafglib.mixins.json"

[[dependencies.mafglib]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mafglib]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.3,)"
ordering = "NONE"
side = "BOTH"
