modLoader = "javafml"
loaderVersion = "[38,)"
license = "LGPLv3"

[[mods]]
modId = "mafglib"
version = "${version}"
displayName = "MaFgLib"
displayURL="https://github.com/ThinkingStudios/MaLiLib-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
MaLiLib unofficial Forge port.

A library mod required by masa's client-side mods.
'''

[[mods]]
modId = "malilib"
version = "${version}"
displayName = "MaFgLib (old modid compat)"
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
MaFgLib old modid compat
'''

[[dependencies.mafglib]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mafglib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"
